### ISSUE TITLE
ErrorProcessOutOfSystemLimits

### ISSUE THREAD

**Issue by jt3456** [MagiMaster/checkio-task-probably-dice#7]
Hi, 
I have this error "ErrorProcessOutOfSystemLimits" when I'm trying to check my solution. For smaller numbers it's working fine, but with 7th test I can't pass, it's just loading forever. Can  something be done with that ? Is it just my coding taking too much server memory or something  ?

**Comment by MagiMaster** [comment]
You should ask this on the checkio.org forums.
